export const DEFAULT_USER_SETTINGS = {
  submitKey: "Enter",
  avatar: "1f603",
  fontSize: 14,
  fontFamily: "",
  theme: "auto",
  tightBorder: false,
  sendPreviewBubble: true,
  enableAutoGenerateTitle: true,
  sidebarWidth: 300,
  enableArtifacts: true,
  enableCodeFold: true,
  disablePromptHint: false,
  dontShowMaskSplashScreen: false,
  hideBuiltinMasks: false,
  ttsConfig: {
    enable: false,
    autoplay: false,
    engine: "openai",
    model: "tts-1",
    voice: "alloy",
    speed: 1.0,
  },
} as const;
